# action.yml
name: 'cPanel UAPI request'
description: 'Request to the cPanel UAPI api'
inputs:
  base_url:
    description: 'Api base url'
    required: true
  user:
    description: 'User authentication'
    required: true
  token:
    description: 'Token authentication'
    required: true
  resource_path:
    description: 'Path to resource, example "/execute/Variables/get_user_information?name=mailbox_format"'
    required: true
  method:
    description: 'Request http method'
    required: true
    default: 'GET'
  fields:
    description: 'Comma-separated list of key-value pairs to include as form data. Default ``'
    default: ''
outputs:
  status_code:
    description: 'Api status code'
  errors:
    description: 'Array of error json strings or empty'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.base_url }}
    - ${{ inputs.user }}
    - ${{ inputs.token }}
    - ${{ inputs.resource_path }}
    - ${{ inputs.method }}
    - ${{ inputs.fields }}